/*
 * Automatically generated C config: don't edit
 * Linux kernel version: 
 * Tue May 30 15:47:00 2017
 */
#define AUTOCONF_INCLUDED

/*
 * Hardware System
 */
#define CONFIG_BOARD_CMOST_MAIN 1
#undef CONFIG_BOARD_ACCORDO2
#undef CONFIG_BOARD_ACCORDO5
#undef CONFIG_MODULE_INTEGRATED
#define CONFIG_MODULE_INDEPENDENT 1

/*
 * Tuner support
 */
#define CONFIG_ETAL_SUPPORT_CMOST 1

/*
 * CMOST flavour
 */
#define CONFIG_ETAL_SUPPORT_CMOST_STAR 1
#undef CONFIG_ETAL_SUPPORT_CMOST_DOT

/*
 * Tuner channels
 */
#define CONFIG_ETAL_SUPPORT_CMOST_DUAL_CHANNEL 1
#undef CONFIG_ETAL_SUPPORT_CMOST_SINGLE_CHANNEL

/*
 * Tuner silicon version (a.k.a CUT)
 */
#undef CONFIG_ETAL_SUPPORT_CMOST_STAR_T_CUT_BC
#undef CONFIG_ETAL_SUPPORT_CMOST_STAR_T_CUT_BF
#undef CONFIG_ETAL_SUPPORT_CMOST_STAR_T_CUT_BG
#define CONFIG_ETAL_SUPPORT_CMOST_STAR_T_CUT_CA	1
#undef CONFIG_ETAL_SUPPORT_CMOST_STAR_T_CUT_DA
#define CONFIG_ETAL_ENABLE_CMOST_SDM_CLOCK 1

/*
 * Digital Co-processor support
 */
#define CONFIG_ETAL_SUPPORT_DCOP 1
#undef CONFIG_ETAL_SUPPORT_DCOP_HDRADIO
#define CONFIG_ETAL_SUPPORT_DCOP_MDR 1
#undef CONFIG_MODULE_DCOP_MDR_SPECIAL_AUDIO_GPIO

/*
 * ETAL options
 */

/*
 * ETAL APIs
 */
#define CONFIG_ETAL_HAVE_ALL_API 1
#undef CONFIG_ETAL_HAVE_SELECTED_API

/*
 * ETAL Optional features
 */
#define CONFIG_ETAL_HAVE_ETALTML 1
#define CONFIG_ETAL_RECEIVER_ALIVE_PERIODIC_CHECK 1
#define CONFIG_ETAL_RECEIVER_ALIVE_PERIOD 5000
#define CONFIG_ETAL_RECEIVER_CHECK_STATE_PERIOD 333
#define CONFIG_ETAL_INIT_CHECK_SILICON_VERSION 1

/*
 * ETALTML options
 */
#define CONFIG_ETALTML_HAVE_RDS 1
#define CONFIG_ETALTML_HAVE_AMFMLANDSCAPE 1
#define CONFIG_ETALTML_HAVE_AMFMLANDSCAPE_FULL 1
#define CONFIG_ETALTML_HAVE_RADIOTEXT 1
#define CONFIG_ETALTML_HAVE_AUTO_SEEK 1
#undef CONFIG_ETALTML_AUTO_SEEK_INTERNAL
#define CONFIG_ETALTML_AUTO_SEEK_EXTERNAL 1
#define CONFIG_ETALTML_HAVE_SCAN 1
#define CONFIG_ETALTML_HAVE_LEARN 1
#undef CONFIG_ETALTML_HAVE_SEAMLESS
#undef CONFIG_ETALTML_HAVE_RDS_STRATEGY

/*
 * Device Communication
 */
#define CONFIG_COMM_DRIVER_EXTERNAL 1
#undef CONFIG_COMM_DRIVER_EMBEDDED
#define CONFIG_COMM_CMOST_I2C 1
#undef CONFIG_COMM_CMOST_SPI
#undef CONFIG_COMM_CMOST_FIRMWARE_FILE
#define CONFIG_COMM_CMOST_FIRMWARE_EMBEDDED 1
#define CONFIG_COMM_CMOST_CUSTOMER_SETTINGS 1
#undef CONFIG_COMM_DRIVER_DIRECT

/*
 * Application Configuration
 */
#define CONFIG_APP_ETAL_LIBRARY 1
#undef CONFIG_APP_ETALCORE_LIBRARY
#undef CONFIG_APP_TUNERDRIVER_LIBRARY
#undef CONFIG_APP_ETAL_TEST
#undef CONFIG_APP_OSALCORE_TESTS
#undef CONFIG_APP_ETAL_DCOP_MDR_FLASH

/*
 * Trace Settings
 */
#define CONFIG_TRACE_ENABLE 1
#define CONFIG_TRACE_ASYNC 1
#undef CONFIG_TRACE_ETAL_SYSLOG

/*
 * Minimum Trace Level Configuration
 */

/*
 * Configure compile time trace levels.
 */

/*
 * Trace messages with lower level will not be compiled into the binary.
 */
#define CONFIG_TRACE_CLASS_OSALCORE 3
#define CONFIG_TRACE_CLASS_ETAL 3
#define CONFIG_TRACE_CLASS_BOOT 3
#define CONFIG_TRACE_CLASS_CMOST 3
#define CONFIG_TRACE_CLASS_TUNERDRIVER 3
#define CONFIG_TRACE_CLASS_HDRADIO 3
#define CONFIG_TRACE_CLASS_STECI 3
#define CONFIG_TRACE_CLASS_IPFORWARD 3
#define CONFIG_ENABLE_CLASS_APP_DABMW 3
#undef CONFIG_ENABLE_CLASS_APP_DABMW_SF
#define CONFIG_TRACE_CLASS_EXTERNAL 3
#define CONFIG_TRACE_DEFAULT_LEVEL 1

/*
 * Other Trace configuration
 */
#define CONFIG_TRACE_INCLUDE_FILTERS 1
#define CONFIG_OSUTIL_TRACE_NUM_FILTERS 8
#undef CONFIG_TRACE_ENABLE_IPFORWARD_LOGFILE

/*
 * Build Environment
 */
#define CONFIG_BUILD_SILENT 1
#define CONFIG_HOST_OS_LINUX 1
#undef CONFIG_HOST_OS_LINUX_EMBEDDED
#define CONFIG_HOST_OS_LINUX_DESKTOP 1
#undef CONFIG_HOST_OS_WIN32
#undef CONFIG_HOST_OS_TKERNEL
#undef CONFIG_COMPILER_GCC_CROSS
#define CONFIG_COMPILER_GCC_NATIVE 1

/*
 * Test and Debug Switches
 */
#undef CONFIG_DEBUG_OSAL
#define CONFIG_DEBUG_SYMBOLS 1
#undef CONFIG_DEBUG_STACK_USAGE
#undef CONFIG_DEBUG_INST_FUNC

/*
 * ETAL build-time and run-time checks
 */
#undef CONFIG_DEBUG_ETAL_CHECKS
