#######
# Files.mk:
#
# PATH_LIB_XXX				path to library folder
# PATH_LIB_XXX_SOURCES		path to library source folder
# LIB_XXX_INCLUDES 			define all include pathes for libXXX
# LIB_XXX_C_SOURCES			define a list of all *.c files
# LIB_XXX_A_SOURCES			define a list of all *.s files
# LIB_XXX_CPP_SOURCES		define a list of all *.cpp files
# LIB_XXX_SOURCES			define a list of all *.c + *.cpp + *.s files
# LIB_XXX_VPATH				define a list of all source file paths
#
####

# clear variables 
PATH_LIB_STREAMDECADAPT= ${WSPATH}/lib_streamdecadapt
PATH_LIB_STREAMDECADAPT_INCLUDES = ${PATH_LIB_STREAMDECADAPT}/include

PATH_LIB_STREAMDECADAPT_SRC = ${PATH_LIB_STREAMDECADAPT}/src

PATH_LIB_STREAMDECADAPT_SOURCES= ${PATH_LIB_STREAMDECADAPT}/src
LIB_STREAMDECADAPT_INCLUDES=
LIB_STREAMDECADAPT_C_SOURCES=
LIB_STREAMDECADAPT_CPP_SOURCES=
LIB_STREAMDECADAPT_A_SOURCES=
LIB_STREAMDECADAPT_SOURCES= ${LIB_STREAMDECADAPT_C_SOURCES} ${LIB_STREAMDECADAPT_CPP_SOURCES} ${LIB_STREAMDECADAPT_A_SOURCES}
LIB_STREAMDECADAPT_VPATH=

LIB_STREAMDECADAPT_C_SOURCES += \
	${PATH_LIB_STREAMDECADAPT_SOURCES}/streamdecadapt.c \
	${PATH_LIB_STREAMDECADAPT_SOURCES}/audioin.c \
	${PATH_LIB_STREAMDECADAPT_SOURCES}/dabdevadapt.c

LIB_STREAMDECADAPT_INCLUDES += \
	-I${PATH_LIB_STREAMDECADAPT_INCLUDES}

LIB_STREAMDECADAPT_VPATH += \
	${PATH_LIB_STREAMDECADAPT_SRC}

### End of file ###
