obj-$(CONFIG_RPMSG)		+= rpmsg_core.o
obj-$(CONFIG_RPMSG_CHAR)	+= rpmsg_char.o
obj-$(CONFIG_RPMSG_QCOM_SMD)	+= qcom_smd.o
obj-$(CONFIG_RPMSG_VIRTIO)	+= virtio_rpmsg_bus.o
obj-$(CONFIG_STA_RPMSG)	+= sta_rpmsg.o
obj-$(CONFIG_STA_RPMSG)	+= sta_rpmsg_mm.o
obj-$(CONFIG_STA_RPMSG_RDM)	+= sta_rpmsg_rdm.o
