/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *file1;
  GtkWidget *file1_menu;
  GtkWidget *load1;
  GtkWidget *image39;
  GtkWidget *save1;
  GtkWidget *image40;
  GtkWidget *save_as1;
  GtkWidget *image41;
  GtkWidget *separator1;
  GtkWidget *quit1;
  GtkWidget *image42;
  GtkWidget *options1;
  GtkWidget *options1_menu;
  GtkWidget *show_name1;
  GtkWidget *show_range1;
  GtkWidget *show_data1;
  GtkWidget *separator2;
  GtkWidget *show_all_options1;
  GtkWidget *show_debug_info1;
  GtkWidget *help1;
  GtkWidget *help1_menu;
  GtkWidget *introduction1;
  GtkWidget *image43;
  GtkWidget *about1;
  GtkWidget *image44;
  GtkWidget *license1;
  GtkWidget *image45;
  GtkWidget *handlebox1;
  GtkWidget *toolbar1;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *tmp_image;
  GtkWidget *button1;
  GtkWidget *toolitem1;
  GtkWidget *vseparator1;
  GtkWidget *button2;
  GtkWidget *button3;
  GtkWidget *toolitem2;
  GtkWidget *vseparator2;
  GtkWidget *button4;
  GtkWidget *button5;
  GtkWidget *button6;
  GtkWidget *toolitem3;
  GtkWidget *vseparator3;
  GtkWidget *button7;
  GtkWidget *button8;
  GtkWidget *hpaned1;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;
  GtkWidget *vpaned1;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview2;
  GtkWidget *scrolledwindow3;
  GtkWidget *textview3;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (window1, "window1");
  gtk_window_set_title (GTK_WINDOW (window1), _("Gtk Kernel Configurator"));
  gtk_window_set_default_size (GTK_WINDOW (window1), 900, 480);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window1), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_set_name (menubar1, "menubar1");
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  file1 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_set_name (file1, "file1");
  gtk_widget_show (file1);
  gtk_container_add (GTK_CONTAINER (menubar1), file1);

  file1_menu = gtk_menu_new ();
  gtk_widget_set_name (file1_menu, "file1_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file1), file1_menu);

  load1 = gtk_image_menu_item_new_with_mnemonic (_("_Load"));
  gtk_widget_set_name (load1, "load1");
  gtk_widget_show (load1);
  gtk_container_add (GTK_CONTAINER (file1_menu), load1);
  gtk_tooltips_set_tip (tooltips, load1, _("Load a config file"), NULL);
  gtk_widget_add_accelerator (load1, "activate", accel_group,
                              GDK_L, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image39 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image39, "image39");
  gtk_widget_show (image39);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (load1), image39);

  save1 = gtk_image_menu_item_new_with_mnemonic (_("_Save"));
  gtk_widget_set_name (save1, "save1");
  gtk_widget_show (save1);
  gtk_container_add (GTK_CONTAINER (file1_menu), save1);
  gtk_tooltips_set_tip (tooltips, save1, _("Save the config in .config"), NULL);
  gtk_widget_add_accelerator (save1, "activate", accel_group,
                              GDK_S, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image40 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image40, "image40");
  gtk_widget_show (image40);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (save1), image40);

  save_as1 = gtk_image_menu_item_new_with_mnemonic (_("Save _as"));
  gtk_widget_set_name (save_as1, "save_as1");
  gtk_widget_show (save_as1);
  gtk_container_add (GTK_CONTAINER (file1_menu), save_as1);
  gtk_tooltips_set_tip (tooltips, save_as1, _("Save the config in a file"), NULL);

  image41 = gtk_image_new_from_stock ("gtk-save-as", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image41, "image41");
  gtk_widget_show (image41);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (save_as1), image41);

  separator1 = gtk_separator_menu_item_new ();
  gtk_widget_set_name (separator1, "separator1");
  gtk_widget_show (separator1);
  gtk_container_add (GTK_CONTAINER (file1_menu), separator1);
  gtk_widget_set_sensitive (separator1, FALSE);

  quit1 = gtk_image_menu_item_new_with_mnemonic (_("_Quit"));
  gtk_widget_set_name (quit1, "quit1");
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (file1_menu), quit1);
  gtk_widget_add_accelerator (quit1, "activate", accel_group,
                              GDK_Q, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image42 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image42, "image42");
  gtk_widget_show (image42);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (quit1), image42);

  options1 = gtk_menu_item_new_with_mnemonic (_("_Options"));
  gtk_widget_set_name (options1, "options1");
  gtk_widget_show (options1);
  gtk_container_add (GTK_CONTAINER (menubar1), options1);

  options1_menu = gtk_menu_new ();
  gtk_widget_set_name (options1_menu, "options1_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (options1), options1_menu);

  show_name1 = gtk_check_menu_item_new_with_mnemonic (_("Show _name"));
  gtk_widget_set_name (show_name1, "show_name1");
  gtk_widget_show (show_name1);
  gtk_container_add (GTK_CONTAINER (options1_menu), show_name1);
  gtk_tooltips_set_tip (tooltips, show_name1, _("Show name"), NULL);

  show_range1 = gtk_check_menu_item_new_with_mnemonic (_("Show _range"));
  gtk_widget_set_name (show_range1, "show_range1");
  gtk_widget_show (show_range1);
  gtk_container_add (GTK_CONTAINER (options1_menu), show_range1);
  gtk_tooltips_set_tip (tooltips, show_range1, _("Show range (Y/M/N)"), NULL);

  show_data1 = gtk_check_menu_item_new_with_mnemonic (_("Show _data"));
  gtk_widget_set_name (show_data1, "show_data1");
  gtk_widget_show (show_data1);
  gtk_container_add (GTK_CONTAINER (options1_menu), show_data1);
  gtk_tooltips_set_tip (tooltips, show_data1, _("Show value of the option"), NULL);

  separator2 = gtk_separator_menu_item_new ();
  gtk_widget_set_name (separator2, "separator2");
  gtk_widget_show (separator2);
  gtk_container_add (GTK_CONTAINER (options1_menu), separator2);
  gtk_widget_set_sensitive (separator2, FALSE);

  show_all_options1 = gtk_check_menu_item_new_with_mnemonic (_("Show all _options"));
  gtk_widget_set_name (show_all_options1, "show_all_options1");
  gtk_widget_show (show_all_options1);
  gtk_container_add (GTK_CONTAINER (options1_menu), show_all_options1);
  gtk_tooltips_set_tip (tooltips, show_all_options1, _("Show all options"), NULL);

  show_debug_info1 = gtk_check_menu_item_new_with_mnemonic (_("Show _debug info"));
  gtk_widget_set_name (show_debug_info1, "show_debug_info1");
  gtk_widget_show (show_debug_info1);
  gtk_container_add (GTK_CONTAINER (options1_menu), show_debug_info1);
  gtk_tooltips_set_tip (tooltips, show_debug_info1, _("Show masked options"), NULL);

  help1 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_set_name (help1, "help1");
  gtk_widget_show (help1);
  gtk_container_add (GTK_CONTAINER (menubar1), help1);

  help1_menu = gtk_menu_new ();
  gtk_widget_set_name (help1_menu, "help1_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help1), help1_menu);

  introduction1 = gtk_image_menu_item_new_with_mnemonic (_("_Introduction"));
  gtk_widget_set_name (introduction1, "introduction1");
  gtk_widget_show (introduction1);
  gtk_container_add (GTK_CONTAINER (help1_menu), introduction1);
  gtk_widget_add_accelerator (introduction1, "activate", accel_group,
                              GDK_I, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image43 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image43, "image43");
  gtk_widget_show (image43);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (introduction1), image43);

  about1 = gtk_image_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_set_name (about1, "about1");
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (help1_menu), about1);
  gtk_widget_add_accelerator (about1, "activate", accel_group,
                              GDK_A, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image44 = gtk_image_new_from_stock ("gtk-properties", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image44, "image44");
  gtk_widget_show (image44);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (about1), image44);

  license1 = gtk_image_menu_item_new_with_mnemonic (_("_License"));
  gtk_widget_set_name (license1, "license1");
  gtk_widget_show (license1);
  gtk_container_add (GTK_CONTAINER (help1_menu), license1);

  image45 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image45, "image45");
  gtk_widget_show (image45);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (license1), image45);

  handlebox1 = gtk_handle_box_new ();
  gtk_widget_set_name (handlebox1, "handlebox1");
  gtk_widget_show (handlebox1);
  gtk_box_pack_start (GTK_BOX (vbox1), handlebox1, FALSE, FALSE, 0);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_set_name (toolbar1, "toolbar1");
  gtk_widget_show (toolbar1);
  gtk_container_add (GTK_CONTAINER (handlebox1), toolbar1);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  tmp_image = gtk_image_new_from_stock ("gtk-undo", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button1 = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Back"));
  gtk_widget_set_name (button1, "button1");
  gtk_widget_show (button1);
  gtk_container_add (GTK_CONTAINER (toolbar1), button1);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button1), tooltips, _("Goes up of one level (single view)"), NULL);

  toolitem1 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_set_name (toolitem1, "toolitem1");
  gtk_widget_show (toolitem1);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolitem1);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_set_name (vseparator1, "vseparator1");
  gtk_widget_show (vseparator1);
  gtk_container_add (GTK_CONTAINER (toolitem1), vseparator1);

  tmp_image = gtk_image_new_from_stock ("gtk-open", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button2 = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Load"));
  gtk_widget_set_name (button2, "button2");
  gtk_widget_show (button2);
  gtk_container_add (GTK_CONTAINER (toolbar1), button2);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button2), tooltips, _("Load a config file"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-save", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button3 = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Save"));
  gtk_widget_set_name (button3, "button3");
  gtk_widget_show (button3);
  gtk_container_add (GTK_CONTAINER (toolbar1), button3);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button3), tooltips, _("Save a config file"), NULL);

  toolitem2 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_set_name (toolitem2, "toolitem2");
  gtk_widget_show (toolitem2);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolitem2);

  vseparator2 = gtk_vseparator_new ();
  gtk_widget_set_name (vseparator2, "vseparator2");
  gtk_widget_show (vseparator2);
  gtk_container_add (GTK_CONTAINER (toolitem2), vseparator2);

  tmp_image = gtk_image_new_from_stock ("gtk-missing-image", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button4 = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Single"));
  gtk_widget_set_name (button4, "button4");
  gtk_widget_show (button4);
  gtk_container_add (GTK_CONTAINER (toolbar1), button4);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button4), tooltips, _("Single view"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-missing-image", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button5 = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Split"));
  gtk_widget_set_name (button5, "button5");
  gtk_widget_show (button5);
  gtk_container_add (GTK_CONTAINER (toolbar1), button5);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button5), tooltips, _("Split view"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-missing-image", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button6 = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Full"));
  gtk_widget_set_name (button6, "button6");
  gtk_widget_show (button6);
  gtk_container_add (GTK_CONTAINER (toolbar1), button6);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button6), tooltips, _("Full view"), NULL);

  toolitem3 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_set_name (toolitem3, "toolitem3");
  gtk_widget_show (toolitem3);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolitem3);

  vseparator3 = gtk_vseparator_new ();
  gtk_widget_set_name (vseparator3, "vseparator3");
  gtk_widget_show (vseparator3);
  gtk_container_add (GTK_CONTAINER (toolitem3), vseparator3);

  tmp_image = gtk_image_new_from_stock ("gtk-remove", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button7 = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Collapse"));
  gtk_widget_set_name (button7, "button7");
  gtk_widget_show (button7);
  gtk_container_add (GTK_CONTAINER (toolbar1), button7);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button7), tooltips, _("Collapse the whole tree in the right frame"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-add", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button8 = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Expand"));
  gtk_widget_set_name (button8, "button8");
  gtk_widget_show (button8);
  gtk_container_add (GTK_CONTAINER (toolbar1), button8);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button8), tooltips, _("Expand the whole tree in the right frame"), NULL);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_set_name (hpaned1, "hpaned1");
  gtk_widget_show (hpaned1);
  gtk_box_pack_start (GTK_BOX (vbox1), hpaned1, TRUE, TRUE, 0);
  gtk_widget_set_size_request (hpaned1, 1, -1);
  gtk_paned_set_position (GTK_PANED (hpaned1), 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow1, "scrolledwindow1");
  gtk_widget_show (scrolledwindow1);
  gtk_paned_pack1 (GTK_PANED (hpaned1), scrolledwindow1, FALSE, TRUE);
  GTK_WIDGET_UNSET_FLAGS (scrolledwindow1, GTK_CAN_FOCUS);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_set_name (treeview1, "treeview1");
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);

  vpaned1 = gtk_vpaned_new ();
  gtk_widget_set_name (vpaned1, "vpaned1");
  gtk_widget_show (vpaned1);
  gtk_paned_pack2 (GTK_PANED (hpaned1), vpaned1, TRUE, TRUE);
  gtk_paned_set_position (GTK_PANED (vpaned1), 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow2, "scrolledwindow2");
  gtk_widget_show (scrolledwindow2);
  gtk_paned_pack1 (GTK_PANED (vpaned1), scrolledwindow2, FALSE, TRUE);
  GTK_WIDGET_UNSET_FLAGS (scrolledwindow2, GTK_CAN_FOCUS);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_IN);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_set_name (treeview2, "treeview2");
  gtk_widget_show (treeview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview2);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow3, "scrolledwindow3");
  gtk_widget_show (scrolledwindow3);
  gtk_paned_pack2 (GTK_PANED (vpaned1), scrolledwindow3, TRUE, TRUE);
  GTK_WIDGET_UNSET_FLAGS (scrolledwindow3, GTK_CAN_FOCUS);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_SHADOW_IN);

  textview3 = gtk_text_view_new ();
  gtk_widget_set_name (textview3, "textview3");
  gtk_widget_show (textview3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), textview3);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (textview3), FALSE);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (textview3), GTK_WRAP_WORD);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview3)), _("Sorry, no help available for this option yet."), -1);

  g_signal_connect_swapped ((gpointer) window1, "destroy",
                            G_CALLBACK (on_window1_destroy),
                            GTK_OBJECT (window1));
  g_signal_connect_swapped ((gpointer) window1, "size_request",
                            G_CALLBACK (on_window1_size_request),
                            GTK_OBJECT (vpaned1));
  g_signal_connect_swapped ((gpointer) window1, "delete_event",
                            G_CALLBACK (on_window1_delete_event),
                            GTK_OBJECT (window1));
  g_signal_connect ((gpointer) load1, "activate",
                    G_CALLBACK (on_load1_activate),
                    NULL);
  g_signal_connect ((gpointer) save1, "activate",
                    G_CALLBACK (on_save1_activate),
                    NULL);
  g_signal_connect ((gpointer) save_as1, "activate",
                    G_CALLBACK (on_save_as1_activate),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (on_quit1_activate),
                    NULL);
  g_signal_connect ((gpointer) show_name1, "activate",
                    G_CALLBACK (on_show_name1_activate),
                    NULL);
  g_signal_connect ((gpointer) show_range1, "activate",
                    G_CALLBACK (on_show_range1_activate),
                    NULL);
  g_signal_connect ((gpointer) show_data1, "activate",
                    G_CALLBACK (on_show_data1_activate),
                    NULL);
  g_signal_connect ((gpointer) show_all_options1, "activate",
                    G_CALLBACK (on_show_all_options1_activate),
                    NULL);
  g_signal_connect ((gpointer) show_debug_info1, "activate",
                    G_CALLBACK (on_show_debug_info1_activate),
                    NULL);
  g_signal_connect ((gpointer) introduction1, "activate",
                    G_CALLBACK (on_introduction1_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);
  g_signal_connect ((gpointer) license1, "activate",
                    G_CALLBACK (on_license1_activate),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_back_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_load_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_save_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_single_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_split_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_full_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_collapse_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_expand_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "cursor_changed",
                    G_CALLBACK (on_treeview2_cursor_changed),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "button_press_event",
                    G_CALLBACK (on_treeview1_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "key_press_event",
                    G_CALLBACK (on_treeview2_key_press_event),
                    NULL);
  g_signal_connect ((gpointer) treeview2, "cursor_changed",
                    G_CALLBACK (on_treeview2_cursor_changed),
                    NULL);
  g_signal_connect ((gpointer) treeview2, "button_press_event",
                    G_CALLBACK (on_treeview2_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) treeview2, "key_press_event",
                    G_CALLBACK (on_treeview2_key_press_event),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window1, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (window1, file1, "file1");
  GLADE_HOOKUP_OBJECT (window1, file1_menu, "file1_menu");
  GLADE_HOOKUP_OBJECT (window1, load1, "load1");
  GLADE_HOOKUP_OBJECT (window1, image39, "image39");
  GLADE_HOOKUP_OBJECT (window1, save1, "save1");
  GLADE_HOOKUP_OBJECT (window1, image40, "image40");
  GLADE_HOOKUP_OBJECT (window1, save_as1, "save_as1");
  GLADE_HOOKUP_OBJECT (window1, image41, "image41");
  GLADE_HOOKUP_OBJECT (window1, separator1, "separator1");
  GLADE_HOOKUP_OBJECT (window1, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (window1, image42, "image42");
  GLADE_HOOKUP_OBJECT (window1, options1, "options1");
  GLADE_HOOKUP_OBJECT (window1, options1_menu, "options1_menu");
  GLADE_HOOKUP_OBJECT (window1, show_name1, "show_name1");
  GLADE_HOOKUP_OBJECT (window1, show_range1, "show_range1");
  GLADE_HOOKUP_OBJECT (window1, show_data1, "show_data1");
  GLADE_HOOKUP_OBJECT (window1, separator2, "separator2");
  GLADE_HOOKUP_OBJECT (window1, show_all_options1, "show_all_options1");
  GLADE_HOOKUP_OBJECT (window1, show_debug_info1, "show_debug_info1");
  GLADE_HOOKUP_OBJECT (window1, help1, "help1");
  GLADE_HOOKUP_OBJECT (window1, help1_menu, "help1_menu");
  GLADE_HOOKUP_OBJECT (window1, introduction1, "introduction1");
  GLADE_HOOKUP_OBJECT (window1, image43, "image43");
  GLADE_HOOKUP_OBJECT (window1, about1, "about1");
  GLADE_HOOKUP_OBJECT (window1, image44, "image44");
  GLADE_HOOKUP_OBJECT (window1, license1, "license1");
  GLADE_HOOKUP_OBJECT (window1, image45, "image45");
  GLADE_HOOKUP_OBJECT (window1, handlebox1, "handlebox1");
  GLADE_HOOKUP_OBJECT (window1, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, toolitem1, "toolitem1");
  GLADE_HOOKUP_OBJECT (window1, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (window1, button2, "button2");
  GLADE_HOOKUP_OBJECT (window1, button3, "button3");
  GLADE_HOOKUP_OBJECT (window1, toolitem2, "toolitem2");
  GLADE_HOOKUP_OBJECT (window1, vseparator2, "vseparator2");
  GLADE_HOOKUP_OBJECT (window1, button4, "button4");
  GLADE_HOOKUP_OBJECT (window1, button5, "button5");
  GLADE_HOOKUP_OBJECT (window1, button6, "button6");
  GLADE_HOOKUP_OBJECT (window1, toolitem3, "toolitem3");
  GLADE_HOOKUP_OBJECT (window1, vseparator3, "vseparator3");
  GLADE_HOOKUP_OBJECT (window1, button7, "button7");
  GLADE_HOOKUP_OBJECT (window1, button8, "button8");
  GLADE_HOOKUP_OBJECT (window1, hpaned1, "hpaned1");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window1, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window1, vpaned1, "vpaned1");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (window1, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (window1, textview3, "textview3");
  GLADE_HOOKUP_OBJECT_NO_REF (window1, tooltips, "tooltips");

  gtk_widget_grab_focus (treeview2);
  gtk_window_add_accel_group (GTK_WINDOW (window1), accel_group);

  return window1;
}

