/*
 * Automatically generated C config: don't edit
 * Linux kernel version: 
 * Fri Mar  7 14:47:56 2008
 */
#define AUTOCONF_INCLUDED

/*
 * IDB (Information Device Block) Config
 */
#define CONFIG_CONFIG_IDB_VERSION_NAME 0x0000
#define CONFIG_CONFIG_IDB_VERSION_DATE 0x060701
#define CONFIG_CONFIG_IDB_SWNUM "8000000000"
#define CONFIG_CONFIG_IDB_HWNUM "8000000000"

/*
 * Target setup
 */
#undef CONFIG_CONFIG_PARADAB
#undef CONFIG_CONFIG_CARDAB
#define CONFIG_CONFIG_ADRWARE 1
#undef CONFIG_CONFIG_VERBOSE_WARNINGS
#undef CONFIG_CONFIG_OSAL

/*
 * -------------------------
 */
#define CONFIG_CONFIG_ADR3 1
#undef CONFIG_CONFIG_ARION
#undef CONFIG_CONFIG_DFIRE2
#undef CONFIG_CONFIG_SUN
#undef CONFIG_CONFIG_WIN32
#undef CONFIG_CONFIG_LINUX

/*
 * Feature setup
 */

/*
 * Radio Feature setup
 */

/*
 * DAB ...
 */

/*
 * Radiomanager Module Setup
 */
#undef CONFIG_CONFIG_RDM_REGION
#undef CONFIG_CONFIG_RDM_LEARN
#undef CONFIG_CONFIG_RDM_PRESET_STATION
#undef CONFIG_CONFIG_ANNOUNCEMENT_SOURCE_DAB
#undef CONFIG_CONFIG_SERV_FOLLOW
#undef CONFIG_CONFIG_TUNER_SWITCH_UNIT
#undef CONFIG_CONFIG_USE_PREDEFINED_DAB_MODE
#undef CONFIG_CONFIG_PTYS
#undef CONFIG_CONFIG_PACKET_MODE
#undef CONFIG_CONFIG_SERV_COMP_EXTENDED
#undef CONFIG_CONFIG_DATA_SERVICES
#undef CONFIG_CONFIG_SERVICE_LINKING

/*
 * Database ...
 */
#undef CONFIG_CONFIG_DB_STORE_SERVICES_AND_LABELS
#undef CONFIG_CONFIG_DB_PRESET_STATION_SUPPORT
#undef CONFIG_CONFIG_ENABLE_DB_GC
#undef CONFIG_CONFIG_DB_REGION_SUPPORT
#undef CONFIG_CONFIG_DB_AM_SUPPORT
#undef CONFIG_CONFIG_DB_FM_SUPPORT
#define CONFIG_CONFIG_NR_SERVICES 60
#define CONFIG_CONFIG_MAX_NUM_COMPS_IN_SERV 12
#define CONFIG_CONFIG_NR_COMPONENTS 30
#define CONFIG_CONFIG_MAX_NUM_USER_APPL_IN_COMP 6
#undef CONFIG_CONFIG_DATABASE_SUPPORT_OLD_LIST_CONCEPT
#define CONFIG_CONFIG_NR_CLUST_IN_SERV 20
#define CONFIG_CONFIG_NR_ENSEMBLES 10
#define CONFIG_CONFIG_NR_SERVS_IN_ENSEMBLE 15

/*
 * Data feature setup
 */

/*
 * Other Feature setup
 */
#undef CONFIG_CONFIG_USE_FLASH_DEVICE
#undef CONFIG_CONFIG_USE_STORAGE_DEVICE
#undef CONFIG_CONFIG_ENABLE_WATCHDOG_MANAGER
#undef CONFIG_CONFIG_ENABLE_MEMORY_MANAGER
#undef CONFIG_CONFIG_ENABLE_MEMORY_BLOCK
#define CONFIG_CONFIG_SRC_ACTIVE_TIME 10
#undef CONFIG_CONFIG_CONTROL_API

/*
 * Tuner Device setup
 */

/*
 * Network setup
 */

/*
 * Debugging
 */

/*
 * TestDABDevice Configuration
 */

/*
 * TigerWare Class Const Setup
 */

/*
 * TigerWare Load Setup
 */
