/*
 * Automatically generated C config: don't edit
 * Linux kernel version: 
 * Mon Jan 29 11:50:24 2018
 */
#define AUTOCONF_INCLUDED

/*
 * Hardware System
 */
#define CONFIG_BOARD_CMOST_MAIN 1
#undef CONFIG_BOARD_ACCORDO2
#undef CONFIG_BOARD_ACCORDO5

/*
 * Tuner module selection
 */
#define CONFIG_MODULE_INTEGRATED 1
#define CONFIG_MODULE_INTEGRATED_WITH_2_TDA7707 1
#undef CONFIG_MODULE_INTEGRATED_WITH_TDA7707_TDA7708
#undef CONFIG_MODULE_INDEPENDENT

/*
 * Tuner support
 */
#define CONFIG_ETAL_SUPPORT_CMOST 1

/*
 * CMOST flavour
 */
#define CONFIG_ETAL_SUPPORT_CMOST_STAR 1
#undef CONFIG_ETAL_SUPPORT_CMOST_DOT

/*
 * Tuner channels
 */
#define CONFIG_ETAL_SUPPORT_CMOST_DUAL_CHANNEL 1
#undef CONFIG_ETAL_SUPPORT_CMOST_SINGLE_CHANNEL

/*
 * Tuner silicon version (a.k.a CUT)
 */
#undef CONFIG_ETAL_SUPPORT_CMOST_STAR_T_CUT_BC
#undef CONFIG_ETAL_SUPPORT_CMOST_STAR_T_CUT_BF
#undef CONFIG_ETAL_SUPPORT_CMOST_STAR_T_CUT_BG
#undef CONFIG_ETAL_SUPPORT_CMOST_STAR_T_CUT_CA
#define CONFIG_ETAL_SUPPORT_CMOST_STAR_T_CUT_DA 1

/*
 * Digital Co-processor support
 */
#define CONFIG_ETAL_SUPPORT_DCOP 1
#undef CONFIG_ETAL_SUPPORT_DCOP_HDRADIO
#define CONFIG_ETAL_SUPPORT_DCOP_MDR 1

/*
 * ETAL options
 */

/*
 * ETAL APIs
 */
#define CONFIG_ETAL_HAVE_ALL_API 1
#undef CONFIG_ETAL_HAVE_SELECTED_API

/*
 * ETAL Optional features
 */
#define CONFIG_ETAL_HAVE_ETALTML 1
#undef CONFIG_ETAL_RECEIVER_ALIVE_PERIODIC_CHECK
#define CONFIG_ETAL_RECEIVER_CHECK_STATE_PERIOD 333
#define CONFIG_ETAL_INIT_CHECK_SILICON_VERSION 1

/*
 * ETALTML options
 */
#define CONFIG_ETALTML_HAVE_RDS 1
#define CONFIG_ETALTML_HAVE_AMFMLANDSCAPE 1
#define CONFIG_ETALTML_HAVE_AMFMLANDSCAPE_FULL 1
#define CONFIG_ETALTML_HAVE_RADIOTEXT 1
#define CONFIG_ETALTML_HAVE_SCAN 1
#define CONFIG_ETALTML_HAVE_SERVICE_FOLLOWING 1
#define CONFIG_ETALTML_HAVE_LEARN 1

/*
 * Device Communication
 */
#define CONFIG_COMM_DRIVER_EXTERNAL 1
#undef CONFIG_COMM_DRIVER_EMBEDDED
#define CONFIG_COMM_CMOST_I2C 1
#undef CONFIG_COMM_CMOST_SPI
#undef CONFIG_COMM_CMOST_HAVE_DEDICATED_RESET_LINE
#undef CONFIG_COMM_CMOST_FIRMWARE_FILE
#undef CONFIG_COMM_CMOST_FIRMWARE_IMAGE
#define CONFIG_COMM_CMOST_FIRMWARE_EMBEDDED 1
#define CONFIG_COMM_CMOST_CUSTOMER_SETTINGS 1
#undef CONFIG_COMM_DRIVER_DIRECT

/*
 * Application Configuration
 */
#define CONFIG_APP_ETAL_LIBRARY 1
#undef CONFIG_APP_ETALCORE_LIBRARY
#undef CONFIG_APP_TUNERDRIVER_LIBRARY
#undef CONFIG_APP_ETAL_TEST
#undef CONFIG_APP_OSALCORE_TESTS
#undef CONFIG_APP_ETAL_DCOP_MDR_FLASH

/*
 * Trace Settings
 */
#define CONFIG_TRACE_ENABLE 1
#undef CONFIG_TRACE_ASYNC
#undef CONFIG_TRACE_ETAL_SYSLOG

/*
 * Minimum Trace Level Configuration
 */

/*
 * Configure compile time trace levels.
 */

/*
 * Trace messages with lower level will not be compiled into the binary.
 */
#define CONFIG_TRACE_CLASS_OSALCORE 3
#define CONFIG_TRACE_CLASS_ETAL 2
#define CONFIG_TRACE_CLASS_BOOT 2
#define CONFIG_TRACE_CLASS_CMOST 2
#define CONFIG_TRACE_CLASS_TUNERDRIVER 2
#define CONFIG_TRACE_CLASS_HDRADIO 2
#define CONFIG_TRACE_CLASS_STECI 2
#define CONFIG_TRACE_CLASS_IPFORWARD 2
#define CONFIG_ENABLE_CLASS_APP_DABMW 2
#undef CONFIG_ENABLE_CLASS_APP_DABMW_SF
#define CONFIG_TRACE_CLASS_EXTERNAL 2
#define CONFIG_TRACE_DEFAULT_LEVEL 2

/*
 * Other Trace configuration
 */
#undef CONFIG_TRACE_INCLUDE_FILTERS
#undef CONFIG_TRACE_ENABLE_IPFORWARD_LOGFILE

/*
 * Build Environment
 */
#define CONFIG_BUILD_SILENT 1
#undef CONFIG_HOST_OS_LINUX
#define CONFIG_HOST_OS_WIN32 1
#undef CONFIG_HOST_OS_TKERNEL
#undef CONFIG_COMPILER_GCC_CROSS
#define CONFIG_COMPILER_GCC_NATIVE 1

/*
 * Test and Debug Switches
 */
#undef CONFIG_DEBUG_OSAL
#define CONFIG_DEBUG_SYMBOLS 1
#undef CONFIG_DEBUG_STACK_USAGE
#undef CONFIG_DEBUG_INST_FUNC

/*
 * ETAL build-time and run-time checks
 */
#undef CONFIG_DEBUG_ETAL_CHECKS
